version: '3.9'
services:
  frontend:
    container_name: 'frontend'
    build: .
    command: 'npm run start'
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
